server:
  port: 9999
  servlet:
    context-path: /lib-server/mg
logging:
  config: classpath:logback-spring.xml
spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/iot?useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: mysql
  main:
    allow-bean-definition-overriding: true
  jpa: 
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 3000
    lettuce:
      pool:
        max-active: 200
        min-idle: 20
        max-idle: 5
  session:
    store-type: redis
    redis:
      namespace: libsys
  jackson:
    time-zone: GMT+8
mybatis-plus:
  global-config:
    id-type: 0
  mapper-locations:
  - classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
libsys: 
  imagesUploadFolder: D:/work/temp/images